//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <objc/NSObject.h>


@class BrightnessSystemClient;

@interface CBBlueLightClient : NSObject
{
    BrightnessSystemClient *bsc;
    id clientBlock;
    BOOL ownsClient;
    BOOL notificationActive;
    BOOL rangeSet;
    id defaultCctRange;
    BOOL rangeOverridden;
    id cctRange;
    BOOL _supported;
}

+ (BOOL)supportsBlueLightReduction;
@property BOOL supported; // @synthesize supported=_supported;
- (BOOL)getWarningStrength:(float *)arg1;
- (BOOL)getWarningCCT:(float *)arg1;
- (BOOL)setStrength:(float)arg1 withPeriod:(float)arg2 commit:(BOOL)arg3;
- (BOOL)setStrength:(float)arg1 commit:(BOOL)arg2;
- (BOOL)getStrength:(float *)arg1;
- (BOOL)setCCTRange:(id *)arg1;
- (BOOL)getCCTRange:(id *)arg1;
- (BOOL)setCCT:(float)arg1 withPeriod:(float)arg2 commit:(BOOL)arg3;
- (BOOL)setCCT:(float)arg1 commit:(BOOL)arg2;
- (BOOL)getCCT:(float *)arg1;
- (BOOL)getDefaultCCTRange:(id *)arg1;
- (void)suspendNotifications:(BOOL)arg1;
- (void)setStatusNotificationBlock:(id )arg1;
- (void)suspendNotifications:(BOOL)arg1 force:(BOOL)arg2;
- (void)enableNotifications;
- (void)disableNotifications;
- (BOOL)getBlueLightStatus:(id *)arg1;
- (BOOL)parseStatusDictionary:(id)arg1 intoStruct:(id *)arg2;
- (BOOL)setSchedule:(const id *)arg1;
- (BOOL)setMode:(int)arg1;
- (BOOL)setEnabled:(BOOL)arg1;
- (BOOL)setEnabled:(BOOL)arg1 withOption:(int)arg2;
- (BOOL)setActive:(BOOL)arg1;
- (void)dealloc;
- (id)init;
- (id)initWithClientObj:(id)arg1;

@end

